name: previsando
# Controls when the action will run.
on:
  schedule:
    - cron:  '0 9 * * *'
jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::dplyr 
            any::fpp3
            any::forecast 
            any::ggplot2
            any::rvest 
            any::lubridate
            any::readxl 
            any::writexl
            
        
    # Run R script
      - name: Generate data
        run: |
          source("R/codigo.R")
        shell: Rscript {0}
      
 # Add new files in data folder, commit along with other modified files, push
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
       
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions          
